name: fcnd
channels:
  - conda-forge
dependencies:
  - python=3.10.13
  - matplotlib=3.6.2
  - jupyter=1.0.0
  - future=0.18.2
  - lxml=4.9.2
  - networkx=2.8.4
  - scikit-image=0.20.0
  - scipy=1.10.1
  - shapely=2.0.1
  - scikit-learn=1.2.2
  - pip
  - pip:
      - git+https://github.com/udacity/udacidrone.git
      - visdom==0.1.7
      - bresenham==0.2
      - msgpack==1.0.2
